# This is a basic workflow to help you get started with Actions

name: Add git tag

# Controls when the workflow will run
on:
  schedule:
    - cron: '50 22 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs commands using the runners shell
      - name: Run a multiple lines script
        run: |
          git config --global user.name 'Jared Huang'
          git config --global user.email 'jared_huang@arcadyan.com.tw'
          TAG_NAME=`date +"v0.%y.%U"`
          git tag ${TAG_NAME}
          git push origin --tags
